"""One instrument-day as a single, time-ordered stream of events.

The simulator reads three planes — book snapshots, trade prints and funding
settlements — and has to see them in one order that a participant could have
seen them in. This module merges them, once, into a struct of arrays: a
timestamp, a kind and a row into the plane that kind names. The event loop then
walks one integer index instead of three cursors.

Ordering at equal timestamps
----------------------------
Funding first, then (in the loop) order activations, then prints, then book
snapshots. Prints before the book that follows them, because the snapshot
already reflects the print: processing it first would count the consumed size
once as a print and again as a cancellation. Activations lose ties to prints, so
an order arriving at a print's exact timestamp misses it — pessimistic by at
most one print per order.

Prints sharing a timestamp and an aggressor are one sweep, and are processed in
the only order price priority allows: a buyer lifts the lowest ask first, so
buys ascend in price and sells descend; at one price, larger prints first, then
the file order. The archives on disk do not preserve the venue's order within a
timestamp, so the order is imposed here rather than inherited. Sells come before
buys at the same timestamp, which is arbitrary but fixed.

Prices are integer ticks
------------------------
Inside the simulator a price is an integer number of ticks. Queue matching asks
"is this print at exactly my price", and on floats that question has the wrong
answer often enough to matter. The tick is derived from the day's own book — the
greatest common divisor of its price levels — and every print must sit on that
grid or the day is refused (:class:`OffGridPrice`), since a print between two
ticks means the data or the tick is wrong.

One day at a time
-----------------
:func:`load_day` reads one instrument-day of each plane from its per-day file
and nothing else, so memory is one day however long the span. A day missing the
book or the prints raises :class:`DayUnavailable`: it is reported, not
simulated.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass
from datetime import UTC, date, datetime
from pathlib import Path

import numpy as np
import pandas as pd

#: Event kinds, in the order they are processed at equal timestamps.
#: Activations are generated by the simulator, never stored in a stream.
FUNDING, ACTIVATION, TRADE, BOOK = 0, 1, 2, 3

NS_PER_S = 1_000_000_000
NS_PER_DAY = 86_400 * NS_PER_S

#: Decimal places tried when deriving a tick or a lot from floats.
_MAX_DECIMALS = 10


class DayUnavailable(RuntimeError):
    """An instrument-day lacks a plane the simulator needs, so it is not simulated."""


class OffGridPrice(ValueError):
    """A price does not sit on the instrument's tick grid."""


@dataclass(frozen=True)
class InstrumentSpec:
    """What the simulator needs to know about an instrument, per day."""

    symbol: str
    #: Price increment. Every book level and every print sits on this grid.
    tick: float
    #: Size increment. Own orders are rounded down to it.
    lot: float
    #: Hours between funding settlements, checked against the history.
    funding_interval_h: int = 8

    def __post_init__(self) -> None:
        if not self.tick > 0:
            raise ValueError(f"tick must be positive, got {self.tick}")
        if not self.lot > 0:
            raise ValueError(f"lot must be positive, got {self.lot}")
        if self.funding_interval_h <= 0 or 24 % self.funding_interval_h:
            raise ValueError(
                f"funding interval must divide a day, got {self.funding_interval_h} hours"
            )


@dataclass(frozen=True)
class DayEvents:
    """One instrument-day as a single time-ordered stream, struct of arrays.

    ``ts``, ``kind`` and ``ref`` are the merged stream: event ``k`` happened at
    ``ts[k]`` and is row ``ref[k]`` of the plane ``kind[k]`` names. The planes
    themselves are below it. Arrays are read-only, so nothing handed to a
    quoter can write into the day.
    """

    spec: InstrumentSpec
    day: date
    ts: np.ndarray
    kind: np.ndarray
    ref: np.ndarray
    book_ts: np.ndarray
    bid_px: np.ndarray
    bid_sz: np.ndarray
    ask_px: np.ndarray
    ask_sz: np.ndarray
    trade_ts: np.ndarray
    trade_px: np.ndarray
    trade_sz: np.ndarray
    trade_aggressor: np.ndarray
    funding_ts: np.ndarray
    funding_rate: np.ndarray
    sequence_gaps: int = 0
    #: False when the day was assembled without a funding plane at all, as
    #: opposed to one with no settlement in it.
    has_funding: bool = True

    @property
    def day_start_ns(self) -> int:
        return day_start_ns(self.day)

    @property
    def depth(self) -> int:
        return int(self.bid_px.shape[1])

    def __len__(self) -> int:
        return len(self.ts)


def day_start_ns(day: date) -> int:
    """Midnight UTC of ``day``, in nanoseconds since the epoch."""
    return int(datetime(day.year, day.month, day.day, tzinfo=UTC).timestamp()) * NS_PER_S


def _decimal_scale(values: np.ndarray) -> int:
    """The fewest decimal places that represent every value exactly."""
    magnitude = np.abs(values)
    for decimals in range(_MAX_DECIMALS + 1):
        scaled = magnitude * 10.0**decimals
        if np.all(np.abs(scaled - np.round(scaled)) <= 1e-6):
            return decimals
    raise OffGridPrice(f"values need more than {_MAX_DECIMALS} decimal places")


def derive_tick(prices: np.ndarray) -> float:
    """The price grid: the greatest common divisor of the distinct prices.

    A ten-level book over a day shows adjacent levels a tick apart many times
    over, so the divisor of the differences is the tick rather than a multiple
    of it.
    """
    values = np.unique(np.asarray(prices, dtype=np.float64))
    values = values[np.isfinite(values)]
    if len(values) < 2:
        raise OffGridPrice("at least two distinct prices are needed to derive a tick")
    decimals = _decimal_scale(values)
    integers = np.round(values * 10.0**decimals).astype(np.int64)
    step = int(np.gcd.reduce(np.diff(integers)))
    return step / 10.0**decimals


def derive_lot(sizes: np.ndarray) -> float:
    """The size grid: the greatest common divisor of the day's print sizes.

    At most the smallest print, and usually the venue's quantity step.
    """
    values = np.unique(np.asarray(sizes, dtype=np.float64))
    values = values[np.isfinite(values) & (values > 0)]
    if len(values) == 0:
        raise ValueError("no positive sizes to derive a lot from")
    decimals = _decimal_scale(values)
    integers = np.round(values * 10.0**decimals).astype(np.int64)
    return int(np.gcd.reduce(integers)) / 10.0**decimals


def to_ticks(prices: np.ndarray, tick: float) -> np.ndarray:
    """Prices as integer ticks, refusing any price off the grid."""
    values = np.asarray(prices, dtype=np.float64)
    ticks = np.round(values / tick)
    off = np.abs(ticks * tick - values) > 1e-6 * tick
    if np.any(off):
        first = float(values.ravel()[np.argmax(off.ravel())])
        raise OffGridPrice(f"price {first!r} is not a multiple of the tick {tick!r}")
    return ticks.astype(np.int64)


def sweep_order(
    ts: np.ndarray, price: np.ndarray, size: np.ndarray, aggressor: np.ndarray
) -> np.ndarray:
    """The permutation that puts prints in time order and each sweep in price order.

    Within a timestamp: sells before buys; buys by ascending price, sells by
    descending price; larger prints first at one price; then the input order
    (the sort is stable).
    """
    aggressor = np.asarray(aggressor, dtype=np.int64)
    keyed_price = aggressor * np.asarray(price, dtype=np.int64)
    return np.lexsort((-np.asarray(size, dtype=np.float64), keyed_price, aggressor, ts))


def _read_only(*arrays: np.ndarray) -> None:
    for array in arrays:
        array.flags.writeable = False


def assemble(
    spec: InstrumentSpec,
    day: date,
    *,
    book_ts: np.ndarray,
    bid_px: np.ndarray,
    bid_sz: np.ndarray,
    ask_px: np.ndarray,
    ask_sz: np.ndarray,
    trade_ts: np.ndarray,
    trade_px: np.ndarray,
    trade_sz: np.ndarray,
    trade_aggressor: np.ndarray,
    funding_ts: np.ndarray | None = None,
    funding_rate: np.ndarray | None = None,
    sequence_gaps: int = 0,
) -> DayEvents:
    """Merge the three planes of one day into a :class:`DayEvents`.

    Book prices and print prices are integer ticks already (see
    :func:`to_ticks`). Prints are put in sweep order and book rows in time
    order before the merge; funding settlements must fall on the
    instrument's settlement grid.
    """
    book_ts = np.asarray(book_ts, dtype=np.int64)
    bid_px, ask_px = np.asarray(bid_px, dtype=np.int64), np.asarray(ask_px, dtype=np.int64)
    bid_sz, ask_sz = np.asarray(bid_sz, dtype=np.float64), np.asarray(ask_sz, dtype=np.float64)
    if bid_px.ndim != 2 or bid_px.shape != ask_px.shape or bid_px.shape != bid_sz.shape:
        raise ValueError("book arrays must be two-dimensional and of one shape")
    if bid_px.shape != ask_sz.shape or bid_px.shape[0] != len(book_ts):
        raise ValueError("book arrays must have one row per book timestamp")
    if len(book_ts) == 0:
        raise DayUnavailable(f"{spec.symbol} {day}: no book snapshots")
    if len(trade_ts) == 0:
        raise DayUnavailable(f"{spec.symbol} {day}: no trade prints")

    order = np.argsort(book_ts, kind="stable")
    book_ts, bid_px, bid_sz, ask_px, ask_sz = (
        book_ts[order],
        bid_px[order],
        bid_sz[order],
        ask_px[order],
        ask_sz[order],
    )

    trade_ts = np.asarray(trade_ts, dtype=np.int64)
    trade_px = np.asarray(trade_px, dtype=np.int64)
    trade_sz = np.asarray(trade_sz, dtype=np.float64)
    trade_aggressor = np.asarray(trade_aggressor, dtype=np.int8)
    if not np.all(np.isin(trade_aggressor, (-1, 1))):
        raise ValueError("an aggressor must be +1 (buyer crossed) or -1 (seller crossed)")
    if np.any(trade_sz <= 0):
        raise ValueError("print sizes must be positive")
    swept = sweep_order(trade_ts, trade_px, trade_sz, trade_aggressor)
    trade_ts, trade_px, trade_sz, trade_aggressor = (
        trade_ts[swept],
        trade_px[swept],
        trade_sz[swept],
        trade_aggressor[swept],
    )

    has_funding = funding_ts is not None
    funding_ts = np.asarray(funding_ts if funding_ts is not None else [], dtype=np.int64)
    funding_rate = np.asarray(funding_rate if funding_rate is not None else [], dtype=np.float64)
    if len(funding_ts) != len(funding_rate):
        raise ValueError("funding timestamps and rates differ in length")
    order = np.argsort(funding_ts, kind="stable")
    funding_ts, funding_rate = funding_ts[order], funding_rate[order]
    interval_ns = spec.funding_interval_h * 3600 * NS_PER_S
    if np.any((funding_ts - day_start_ns(day)) % interval_ns):
        raise ValueError(
            f"{spec.symbol} {day}: a funding settlement is off the "
            f"{spec.funding_interval_h}-hour grid"
        )

    kinds = np.concatenate(
        [
            np.full(len(funding_ts), FUNDING, dtype=np.int8),
            np.full(len(trade_ts), TRADE, dtype=np.int8),
            np.full(len(book_ts), BOOK, dtype=np.int8),
        ]
    )
    refs = np.concatenate(
        [
            np.arange(len(funding_ts), dtype=np.int64),
            np.arange(len(trade_ts), dtype=np.int64),
            np.arange(len(book_ts), dtype=np.int64),
        ]
    )
    stamps = np.concatenate([funding_ts, trade_ts, book_ts])
    merged = np.lexsort((refs, kinds, stamps))
    ts, kind, ref = stamps[merged], kinds[merged], refs[merged]

    _read_only(
        ts,
        kind,
        ref,
        book_ts,
        bid_px,
        bid_sz,
        ask_px,
        ask_sz,
        trade_ts,
        trade_px,
        trade_sz,
        trade_aggressor,
        funding_ts,
        funding_rate,
    )
    return DayEvents(
        spec=spec,
        day=day,
        ts=ts,
        kind=kind,
        ref=ref,
        book_ts=book_ts,
        bid_px=bid_px,
        bid_sz=bid_sz,
        ask_px=ask_px,
        ask_sz=ask_sz,
        trade_ts=trade_ts,
        trade_px=trade_px,
        trade_sz=trade_sz,
        trade_aggressor=trade_aggressor,
        funding_ts=funding_ts,
        funding_rate=funding_rate,
        sequence_gaps=int(sequence_gaps),
        has_funding=has_funding,
    )


def to_ns(stamps: pd.Series | pd.DatetimeIndex) -> np.ndarray:
    """Timestamps as int64 nanoseconds since the epoch, UTC."""
    index = pd.DatetimeIndex(stamps)
    if index.tz is not None:
        index = index.tz_convert("UTC").tz_localize(None)
    return index.as_unit("ns").to_numpy().astype(np.int64)


def _book_path(symbol: str, day: date, roots: Sequence[Path]) -> Path | None:
    for root in roots:
        path = Path(root) / symbol / f"{day.isoformat()}.parquet"
        if path.exists() and path.stat().st_size > 0:
            return path
    return None


def load_day(
    symbol: str,
    day: date,
    *,
    book_roots: Sequence[Path],
    trades_root: Path,
    funding_root: Path | None,
    depth: int = 10,
    funding_interval_h: int = 8,
) -> DayEvents:
    """Read one instrument-day of book, prints and funding, and merge them.

    ``book_roots`` are tried in order (the original book and a later fetch can
    live under different roots). ``funding_root=None`` assembles the day without
    a funding plane, which the result records; a root given without the day's
    file raises, because a funding plane that silently went missing would
    change a result without anything failing.

    Print timestamps are rounded to the microsecond: the archive writes them as
    float seconds, and the conversion leaves nanosecond noise that would break
    ties with book timestamps arbitrarily.
    """
    from trading_research.data import bybit_funding, bybit_trades

    path = _book_path(symbol, day, book_roots)
    if path is None:
        raise DayUnavailable(f"{symbol} {day}: no book under {[str(r) for r in book_roots]}")
    try:
        trades = bybit_trades.load_day(symbol, day, trades_root)
    except bybit_trades.BybitTradesError as exc:
        raise DayUnavailable(f"{symbol} {day}: {exc}") from exc

    columns = ["timestamp"] + [
        f"{side}_{what}_{level}"
        for level in range(depth)
        for side in ("bid", "ask")
        for what in ("price", "size")
    ]
    book = pd.read_parquet(path, columns=columns)
    gaps = int(book.attrs.get("sequence_gaps", 0))
    if book.empty:
        raise DayUnavailable(f"{symbol} {day}: the book file has no rows")

    def plane(side: str, what: str) -> np.ndarray:
        names = [f"{side}_{what}_{level}" for level in range(depth)]
        return book[names].to_numpy(dtype=np.float64)

    bid_price, ask_price = plane("bid", "price"), plane("ask", "price")
    tick = derive_tick(np.concatenate([bid_price.ravel(), ask_price.ravel()]))
    lot = derive_lot(trades["size"].to_numpy(dtype=np.float64))
    spec = InstrumentSpec(symbol, tick, lot, funding_interval_h)

    trade_ts = to_ns(trades["timestamp"])
    trade_ts = (trade_ts + 500) // 1000 * 1000

    funding_ts: np.ndarray | None = None
    funding_rate: np.ndarray | None = None
    if funding_root is not None:
        try:
            funding = bybit_funding.load_day(symbol, day, funding_root)
        except bybit_funding.BybitFundingError as exc:
            raise DayUnavailable(f"{symbol} {day}: {exc}") from exc
        interval = bybit_funding.settlement_interval_h(funding["timestamp"])
        if interval is not None and interval != funding_interval_h:
            raise ValueError(
                f"{symbol} {day}: funding settles every {interval} h, "
                f"not the {funding_interval_h} h assumed"
            )
        funding_ts = to_ns(funding["timestamp"])
        funding_rate = funding["rate"].to_numpy(dtype=np.float64)

    return assemble(
        spec,
        day,
        book_ts=to_ns(book["timestamp"]),
        bid_px=to_ticks(bid_price, tick),
        bid_sz=plane("bid", "size"),
        ask_px=to_ticks(ask_price, tick),
        ask_sz=plane("ask", "size"),
        trade_ts=trade_ts,
        trade_px=to_ticks(trades["price"].to_numpy(dtype=np.float64), tick),
        trade_sz=trades["size"].to_numpy(dtype=np.float64),
        trade_aggressor=trades["aggressor"].to_numpy(dtype=np.int8),
        funding_ts=funding_ts,
        funding_rate=funding_rate,
        sequence_gaps=gaps,
    )
