"""Posting instead of crossing, with the queue that makes it hard.

Every result in this project so far assumes taking liquidity: a model that wants
to act now pays the spread and two taker fees, about 12 to 16 basis points a
round trip on the instruments studied. The gross edge measured across the
corrected searches is 3 to 8 basis points. The gap is the whole finding, and
posting is the only lever that attacks the larger side of it — a Bybit maker fee
is 0.02% against 0.055%, and a filled passive order earns the spread rather than
paying it.

The reason that is not simply better
------------------------------------
A resting order does not choose when it fills. It fills when someone crosses
into it, and people cross into a bid when they want to sell — which is
disproportionately when the price is about to fall. The fills a passive strategy
gets are drawn from the losing half of the distribution, and the favourable
moves, where the market ticks up and leaves the order behind, are precisely the
ones it misses.

That asymmetry is called adverse selection, and it is not a correction to be
subtracted afterwards. It is generated by the fill mechanism, so the only honest
way to measure it is to simulate the mechanism: post, sit in the queue, fill
when the queue in front is consumed, and give up when the market moves away.

The queue is the model
----------------------
An order joins the back of the size already resting at its price. It moves
forward only as aggressive volume on the opposite side trades through that
price. So the state of one posted order is a single number — how much size is
still ahead of it — and three things can happen next:

* enough opposing volume trades at the price to consume that number, and the
  order **fills**;
* the touch moves away from the price and the order is left resting behind the
  market, where it waits without progress until it is **cancelled** on timeout;
* the timeout expires first and the order is cancelled unfilled — a **miss**,
  which costs nothing directly and costs everything in opportunity.

Three optimisms, stated rather than buried
------------------------------------------
1. The queue ahead is taken as the visible size at the posting price and is
   never added to. Real queues grow behind *and* in front as others post.
2. Cancellations ahead of the order are ignored, which would help it — but so
   are the far more numerous cancellations that happen *because* the market is
   moving, which would hurt.
3. The order's own size is treated as negligible, so it never moves the book
   and always fills in full.

Every one of those flatters the passive strategy. If it loses under this model,
it loses under a real one.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

#: Sides, matching the project's direction convention.
BUY, SELL = 1, -1


@dataclass(frozen=True)
class MakerCosts:
    """What a passive round trip costs, before the market moves.

    ``fee_bp_per_side`` is the venue's maker rate — 0.02% on Bybit USDT
    perpetuals, against 0.055% for taking. ``taker_fee_bp_per_side`` applies to
    whichever leg has to cross, since an exit that must happen now cannot wait
    in a queue.
    """

    fee_bp_per_side: float = 2.0
    taker_fee_bp_per_side: float = 5.5
    #: Charged on a crossing leg only. A passive fill has no slippage by
    #: construction: the price was named in advance.
    slippage_bp: float = 0.5

    def __post_init__(self) -> None:
        for name in ("fee_bp_per_side", "taker_fee_bp_per_side", "slippage_bp"):
            if getattr(self, name) < 0:
                raise ValueError(f"{name} must not be negative, got {getattr(self, name)}")

    def round_trip_bp(self, *, passive_exit: bool, spread_bp: float = 0.0) -> float:
        """Cost of entering passively and leaving either way.

        A passive exit pays two maker fees and no spread. A crossing exit pays a
        maker fee in, a taker fee out, plus the spread and slippage on the leg
        that crosses.
        """
        if passive_exit:
            return 2.0 * self.fee_bp_per_side
        return self.fee_bp_per_side + self.taker_fee_bp_per_side + self.slippage_bp + spread_bp


@dataclass(frozen=True)
class PostingRules:
    """How an order is placed and how long it is left there.

    ``timeout_rows``
        Rows the order rests before being cancelled. The single most important
        parameter: a long timeout fills more often, and the extra fills are the
        ones the market took its time to reach, which is to say the worse ones.
    ``join_touch``
        Post at the best price on the signal's side (``True``), or one tick
        behind it (``False``). Posting behind fills less and is selected
        against less.
    ``hold_rows``
        Rows the filled position is kept.
    ``passive_exit``
        Leave by posting on the other side, or cross out at the end of the hold.
        A passive exit is cheaper and may not happen; the model requires it to
        fill under the same queue rules, and crosses out if it does not.
    """

    timeout_rows: int = 60
    join_touch: bool = True
    hold_rows: int = 60
    passive_exit: bool = False

    def __post_init__(self) -> None:
        if self.timeout_rows < 1:
            raise ValueError(f"timeout_rows must be at least 1, got {self.timeout_rows}")
        if self.hold_rows < 1:
            raise ValueError(f"hold_rows must be at least 1, got {self.hold_rows}")


@dataclass(frozen=True)
class MakerTrade:
    """One passive attempt, filled or not."""

    signal_index: int
    direction: int
    filled: bool
    #: Row the order filled on, or -1 if it never did.
    fill_index: int = -1
    fill_price: float = float("nan")
    exit_index: int = -1
    exit_price: float = float("nan")
    #: Rows spent waiting in the queue before filling.
    wait_rows: int = 0
    #: Size that was ahead of the order when it was posted.
    queue_ahead: float = 0.0
    exit_reason: str = "unfilled"
    exit_crossed: bool = False


def _consumed(volume_at: np.ndarray, start: int, stop: int) -> np.ndarray:
    """Cumulative opposing volume traded at or through the posting price."""
    return np.cumsum(volume_at[start:stop])


def simulate(
    decision: np.ndarray,
    bid_price: np.ndarray,
    ask_price: np.ndarray,
    bid_size: np.ndarray,
    ask_size: np.ndarray,
    sell_volume_at_bid: np.ndarray,
    buy_volume_at_ask: np.ndarray,
    rules: PostingRules,
    *,
    tick: float = 0.0,
) -> list[MakerTrade]:
    """Walk the book, posting where the signal says and filling by queue order.

    ``sell_volume_at_bid`` is aggressive selling that traded at or below the
    best bid on each row, and ``buy_volume_at_ask`` its mirror. Those are what
    consume a resting bid and a resting ask respectively.

    One order at a time, as everywhere else in this project: a new signal is
    ignored while an attempt is live, so the result cannot be inflated by
    stacking overlapping positions.
    """
    n = len(decision)
    for name, array in (
        ("bid_price", bid_price),
        ("ask_price", ask_price),
        ("bid_size", bid_size),
        ("ask_size", ask_size),
        ("sell_volume_at_bid", sell_volume_at_bid),
        ("buy_volume_at_ask", buy_volume_at_ask),
    ):
        if len(array) != n:
            raise ValueError(f"{name} has {len(array)} rows, decision has {n}")

    trades: list[MakerTrade] = []
    i = 0
    while i < n:
        side = int(decision[i])
        if side == 0:
            i += 1
            continue

        if side == BUY:
            price = bid_price[i] - (0.0 if rules.join_touch else tick)
            queue = bid_size[i] if rules.join_touch else 0.0
            opposing, touch = sell_volume_at_bid, bid_price
        else:
            price = ask_price[i] + (0.0 if rules.join_touch else tick)
            queue = ask_size[i] if rules.join_touch else 0.0
            opposing, touch = buy_volume_at_ask, ask_price

        if not np.isfinite(price) or not np.isfinite(queue):
            i += 1
            continue

        stop = min(n, i + rules.timeout_rows + 1)
        filled_at = -1
        ahead = float(queue)
        for j in range(i + 1, stop):
            # Volume only helps while the order is still at the touch. Once the
            # market has moved past the posting price, prints happen elsewhere
            # and the order sits behind them making no progress — which is
            # exactly the case where the move went the way the signal wanted.
            if touch[j] == price:
                ahead -= float(opposing[j])
                if ahead <= 0.0:
                    filled_at = j
                    break
            elif (side == BUY and touch[j] < price) or (side == SELL and touch[j] > price):
                # The touch has moved through the price: everything resting
                # there, this order included, has been taken.
                filled_at = j
                break

        if filled_at < 0:
            trades.append(
                MakerTrade(signal_index=i, direction=side, filled=False, queue_ahead=float(queue))
            )
            i = stop
            continue

        exit_at = min(n - 1, filled_at + rules.hold_rows)
        crossed = True
        exit_price = ask_price[exit_at] if side == SELL else bid_price[exit_at]
        reason = "crossed_out"

        if rules.passive_exit:
            # Leaving passively means resting on the other side and being taken
            # there too — under the same queue rules, so a passive exit that
            # never fills becomes a crossing exit at the end of the hold.
            want = ask_price[filled_at] if side == BUY else bid_price[filled_at]
            exit_queue = ask_size[filled_at] if side == BUY else bid_size[filled_at]
            exit_flow = buy_volume_at_ask if side == BUY else sell_volume_at_bid
            exit_touch = ask_price if side == BUY else bid_price
            remaining = float(exit_queue)
            for j in range(filled_at + 1, exit_at + 1):
                if exit_touch[j] == want:
                    remaining -= float(exit_flow[j])
                    if remaining <= 0.0:
                        exit_at, exit_price, crossed, reason = j, want, False, "posted_out"
                        break
                elif (side == BUY and exit_touch[j] > want) or (
                    side == SELL and exit_touch[j] < want
                ):
                    exit_at, exit_price, crossed, reason = j, want, False, "posted_out"
                    break

        trades.append(
            MakerTrade(
                signal_index=i,
                direction=side,
                filled=True,
                fill_index=filled_at,
                fill_price=float(price),
                exit_index=int(exit_at),
                exit_price=float(exit_price),
                wait_rows=filled_at - i,
                queue_ahead=float(queue),
                exit_reason=reason,
                exit_crossed=crossed,
            )
        )
        i = max(exit_at, i + 1)

    return trades


def score(trades: list[MakerTrade], costs: MakerCosts, spread_bp: np.ndarray) -> dict[str, float]:
    """Turn passive attempts into basis points, counting the misses.

    ``fill_rate`` and the per-*attempt* figure matter as much as the per-fill
    one. A strategy that fills a tenth of the time is a different strategy from
    the one that was signalled, and reporting only the fills would hide that.
    """
    if not trades:
        return {"attempts": 0.0, "fills": 0.0, "fill_rate": float("nan")}

    filled = [t for t in trades if t.filled]
    if not filled:
        return {
            "attempts": float(len(trades)),
            "fills": 0.0,
            "fill_rate": 0.0,
            "net_per_fill_bp": float("nan"),
            "net_bp": 0.0,
        }

    gross, net = [], []
    for trade in filled:
        move = (trade.exit_price / trade.fill_price - 1.0) * 1e4 * trade.direction
        cost = costs.round_trip_bp(
            passive_exit=not trade.exit_crossed,
            spread_bp=float(spread_bp[trade.exit_index]),
        )
        gross.append(move)
        net.append(move - cost)

    net_array = np.asarray(net)
    equity = np.cumsum(net_array)
    peak = np.maximum.accumulate(np.maximum(equity, 0.0))
    return {
        "attempts": float(len(trades)),
        "fills": float(len(filled)),
        "fill_rate": float(len(filled) / len(trades)),
        "gross_per_fill_bp": float(np.mean(gross)),
        "cost_per_fill_bp": float(np.mean(np.asarray(gross) - net_array)),
        "net_per_fill_bp": float(np.mean(net_array)),
        # Spread over every attempt, so a low fill rate is visible in the number
        # a strategy is judged on rather than only in a footnote.
        "net_per_attempt_bp": float(np.sum(net_array) / len(trades)),
        "net_bp": float(np.sum(net_array)),
        "hit_rate": float(np.mean(net_array > 0)),
        "median_wait_rows": float(np.median([t.wait_rows for t in filled])),
        "passive_exit_share": float(np.mean([not t.exit_crossed for t in filled])),
        "max_drawdown_bp": float(np.max(peak - equity)) if len(equity) else 0.0,
    }
